# Generated by Django 6.0.3 on 2026-03-16 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'configuração da empresa', 'verbose_name_plural': 'configurações da empresa'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['company__name', 'user__id'], 'verbose_name': 'vínculo do usuário', 'verbose_name_plural': 'vínculos dos usuários'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'unidade', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'equipe', 'verbose_name_plural': 'equipes'},
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('SITE', 'Site/Unidade')], db_index=True, default='SITE', max_length=16, verbose_name='escopo padrão'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='receipt_policy',
            field=models.CharField(choices=[('CONFIRM_ONLY', 'Apenas confirmação'), ('SIGNATURE_REQUIRED', 'Assinatura obrigatória')], db_index=True, default='CONFIRM_ONLY', max_length=32, verbose_name='política de recibo'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.team', verbose_name='equipe')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro da equipe',
                'verbose_name_plural': 'membros da equipe',
                'ordering': ['team__company__name', 'team__name', 'user__id'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
