# Generated by Django 6.0.3 on 2026-03-16 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('SITE', 'Site/Unit')], db_index=True, default='SITE', max_length=16, verbose_name='escopo')),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='iniciado em')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='finalizado em')),
                ('subject', models.CharField(max_length=255, verbose_name='assunto')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELIVERED', 'Delivered'), ('ACKED', 'Acknowledged'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=16, verbose_name='status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='accounts.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_delivered', to=settings.AUTH_USER_MODEL, verbose_name='entregue por')),
                ('recipients_teams', models.ManyToManyField(blank=True, related_name='handovers_to_receive_teams', to='accounts.team', verbose_name='destinatários (equipes)')),
                ('recipients_users', models.ManyToManyField(blank=True, related_name='handovers_to_receive_users', to=settings.AUTH_USER_MODEL, verbose_name='destinatários (usuários)')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='accounts.shift', verbose_name='turno')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='accounts.site', verbose_name='unidade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], db_index=True, default='MED', max_length=8, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('OPEN', 'Open/Pending'), ('DONE', 'Done'), ('INFO', 'Info-only')], db_index=True, default='OPEN', max_length=8, verbose_name='status')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='prazo')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_items_assigned', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handover.handover', verbose_name='entrega')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('file', models.FileField(upload_to='handover_attachments/', verbose_name='arquivo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='handover.handover', verbose_name='entrega')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='handover.handoveritem', verbose_name='item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='accounts.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='handoveritem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='handover.itemcategory', verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='handoveritem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='handover.tag', verbose_name='etiquetas'),
        ),
        migrations.CreateModel(
            name='HandoverRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='confirmado em')),
                ('confirmation_type', models.CharField(choices=[('CONFIRM', 'Confirm'), ('SIGNATURE', 'Signature')], default='CONFIRM', max_length=16, verbose_name='tipo de confirmação')),
                ('comment', models.TextField(blank=True, verbose_name='comentário')),
                ('signature_ref', models.CharField(blank=True, max_length=255, verbose_name='referência da assinatura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_receipts', to='handover.handover', verbose_name='entrega')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_receipts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('handover', 'user')},
            },
        ),
    ]
