# Generated by Django 6.0.3 on 2026-03-16 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handover',
            options={'ordering': ['-starts_at', '-created_at'], 'verbose_name': 'passagem de plantão', 'verbose_name_plural': 'passagens de plantão'},
        ),
        migrations.AlterModelOptions(
            name='handoverattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'anexo', 'verbose_name_plural': 'anexos'},
        ),
        migrations.AlterModelOptions(
            name='handoveritem',
            options={'ordering': ['-created_at'], 'verbose_name': 'item da passagem', 'verbose_name_plural': 'itens da passagem'},
        ),
        migrations.AlterModelOptions(
            name='handoverrecipient',
            options={'ordering': ['-created_at'], 'verbose_name': 'recibo do destinatário', 'verbose_name_plural': 'recibos dos destinatários'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'categoria de item', 'verbose_name_plural': 'categorias de itens'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='handover',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('SITE', 'Site/Unidade')], db_index=True, default='SITE', max_length=16, verbose_name='escopo'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='starts_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='handover',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('DELIVERED', 'Entregue'), ('ACKED', 'Recebido/Confirmado'), ('CLOSED', 'Fechado')], db_index=True, default='DRAFT', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='handoverattachment',
            name='handover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='handover.handover', verbose_name='passagem de plantão'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='handover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handover.handover', verbose_name='passagem de plantão'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MED', 'Média'), ('HIGH', 'Alta')], db_index=True, default='MED', max_length=8, verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto/Pendente'), ('DONE', 'Resolvido'), ('INFO', 'Informativo')], db_index=True, default='OPEN', max_length=8, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='handover.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='handoverrecipient',
            name='confirmation_type',
            field=models.CharField(choices=[('CONFIRM', 'Confirmação'), ('SIGNATURE', 'Assinatura')], default='CONFIRM', max_length=16, verbose_name='tipo de confirmação'),
        ),
        migrations.AlterField(
            model_name='handoverrecipient',
            name='handover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_receipts', to='handover.handover', verbose_name='passagem de plantão'),
        ),
        migrations.AlterField(
            model_name='handoverrecipient',
            name='signature_ref',
            field=models.CharField(blank=True, max_length=255, verbose_name='referência de assinatura'),
        ),
    ]
